with accident_data as
(   select
        cast(ACCIDENT_INDEX as varchar(100)) as ACCIDENT_INDEX,
        cast(ACCIDENT_YEAR as  number(4)) as ACCIDENT_YEAR,
        cast(ACCIDENT_REFERENCE as varchar(100)) as ACCIDENT_REFERENCE,
        cast(location_easting_osgr as varchar(100)) as location_easting_osgr,
        cast(LOCATION_NORTHING_OSGR as varchar(100)) as location_northing_osgr,
        cast( longitude as varchar(100)) as  longitude,
        cast(latitude as varchar(100)) as  latitude,
        cast( police_force as number(2)) as  police_force ,
        cast(accident_severity  as  number(1))as accident_severity ,
        cast(number_of_vehicles as number(3))as number_of_vehicles,
        cast(number_of_casualties  as  number(3))as number_of_casualties  ,
        cast(date as varchar(12)) as  date,
        cast( day_of_week  as number(1))as  day_of_week ,
        cast(  time   as time)as  time  ,
        cast(  local_authority_district  as number(4))as  local_authority_district  ,
        cast( local_authority_ons_district  as varchar(11))as  local_authority_ons_district ,
        cast( local_authority_highway  as varchar(11))as local_authority_highway ,
        cast( first_road_class   as number(1))as first_road_class   ,
        cast( first_road_number  as number(4))as first_road_number  ,
        cast(  road_type     as number(2))as  road_type     ,
        cast(  speed_limit   as number(3))as  speed_limit  ,
        cast( junction_detail as number(2))as junction_detail ,
        cast( junction_control  as number(2))as junction_control  ,
        cast( second_road_class  as number(1))as second_road_class  ,
        cast( second_road_number as number(4))as second_road_number,
        cast(  pedestrian_crossing_human_control as number(1))as  pedestrian_crossing_human_control ,
        cast(pedestrian_crossing_physical_facilities as number(1))as pedestrian_crossing_physical_facilities,
        cast(light_conditions as number(1))as light_conditions ,
        cast(weather_conditions  as number(1))as  weather_conditions  ,
        cast(road_surface_conditions  as number(1))as  road_surface_conditions,
        cast(special_conditions_at_site  as number(1))as special_conditions_at_site  ,
        cast(carriageway_hazards   as number(1))as   carriageway_hazards   ,
        cast(urban_or_rural_area  as number(1))as  urban_or_rural_area,
        cast(did_police_officer_attend_scene_of_accident  as varchar(10))as did_police_officer_attend_scene_of_accident  ,
        cast(  trunk_road_flag    as number(1))as    trunk_road_flag    ,
        cast(lsoa_of_accident_location  as varchar(15))as  lsoa_of_accident_location,
        cast( hub_accident_hash as varchar(200))as hub_accident_hash ,
        cast( inserted_by as varchar(200))as inserted_by,
        cast(SAT_EFF_DATE as timestamp) as  SAT_EFF_DATE
from {{ source('accident_src', 'accident_landing') }}
)

select * from accident_data